# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-4151-ubuntults-VirtualBox/incrSyn
set_param chipscope.maxJobs 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a50ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.cache/wt [current_project]
set_property parent.project_path /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys-a7-50t:part0:1.0 [current_project]
set_property ip_output_repo /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/imports/sources_1/new/defs.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/new/ControlUnit.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/new/CounterMod16.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/new/DisplayManager.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/imports/sources_1/new/HiddenLayer.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/imports/sources_1/imports/Desktop/HiddenLayerNeuron.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/new/InputManager.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/new/Max.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/imports/sources_1/new/MicroROM.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/imports/sources_1/new/Network.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/imports/sources_1/new/OutputLayer.vhd
  {/home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/imports/sources_1/imports/Telegram Desktop/OutputLayerNeuron.vhd}
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/imports/sources_1/new/clock_filter.vhd
  /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/sources_1/new/NeuralNetworkOnBoard.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/constrs_1/imports/Esercizio13_ReteNeurale_con_ControlUnit/Nexys-A7-50T-Master.xdc
set_property used_in_implementation false [get_files /home/ubuntults/Downloads/Esercizio13_ReteNeurale_con_ControlUnit/Esercizio13_ReteNeurale/Esercizio13_ReteNeurale.srcs/constrs_1/imports/Esercizio13_ReteNeurale_con_ControlUnit/Nexys-A7-50T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top NeuralNetworkOnBoard -part xc7a50ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NeuralNetworkOnBoard.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NeuralNetworkOnBoard_utilization_synth.rpt -pb NeuralNetworkOnBoard_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
